### ISSUE TITLE
Version detection doesn't seem to work for some instances

### ISSUE THREAD

**Issue by nilesr** [Juerd/tootpick#3]
Entering "ferretfrizz.biz" (which reports version 3.5.3) results in "That does not appear to be a Mastodon server."

**Comment by Juerd** [comment]
Thanks. I have not been able to reproduce this issue (which was also reported by someone else (not on github)). When I enter that server domain, it works as intended.

Can you provide information about the request to /api/v1/instance as reported in the network tab of your browser's developer tools (F12)?

**Comment by Juerd** [comment]
Probably fixed with c823060b. If not, please reopen.
